name: Build Flet Android APK



on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

env:
  UV_PYTHON: 3.12
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Build APK
        shell: bash
        run: |
          uv run flet build apk --yes --verbose

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v5
        with:
          name: flet-apk-build
          path: build/apk
          if-no-files-found: error
